export const config = {
  version: "V 2.0.0",
  releaseDate: "2022.06.06",
  copyright: "Copyright 2021-2022 Kanagawa Institute of Technology",
  serverUrl1: "https://webapiechonet.com/elapi/v1",
  serverUrl2: "https://www.smarthouse-center.org/elapi/v1",
  // ログをダウンロードする場合のファイル名
  fileName4Log: "log_elapi.txt",
  // デバイス追加に表示するデバイス名のリスト
  addDeviceList: [
    "temperatureSensor",
    "electricEnergySensor",
    "currentSensor",
    "homeAirConditioner",
    "airConditionerVentilationFan",
    "instantaneousWaterHeater",
    "coldOrHotWaterHeatSourceEquipment",
    "fuelCell",
    "storageBattery",
    "evChargerDischarger",
    "lvSmartElectricEnergyMeter",
    "hvSmartElectricEnergyMeter",
    "generalLighting",
    "evCharger",
    "enhancedLightingSystem",
    "controller",
    "ventilationFan",
    "airCleaner",
    "commercialAirConditionerIndoorUnit",
    "commercialAirConditionerOutdoorUnit",
    "electricRainDoor",
    "electricWaterHeater",
    "electricLock",
    "bathroomHeaterDryer",
    "pvPowerGeneration",
    "wattHourMeter",
    "floorHeater",
    "powerDistributionBoardMetering",
    "monoFunctionalLighting",
    "refrigerator",
    "cookingHeater",
    "riceCooker",
    "commercialShowcase",
    "commercialShowcaseOutdoorUnit",
    "switch",
    "hybridWaterHeater",
    "washerDryer",
    "tv",
  ],
};
