// config.ts
// 定数の定義

export const config = {
  version: "V2.1.0",
  releaseDate: "2023.06.01",
  copyright: "Copyright 2021-2023 Kanagawa Institute of Technology",
  serverUrl1: "https://webapiechonet.com/elapi/v1",
  serverUrl2: "https://www.smarthouse-center.org/elapi/v1",
  // コンソ限定バージョン（実証システム関連を非表示）の場合は true とする
  forConsortium: true,
  // ログをダウンロードする場合のファイル名
  fileName4Log: "log_elapi.txt",
  // デバイス追加に表示するデバイス名のリスト
  addDeviceList: [
    "airCleaner",
    "airConditionerVentilationFan",
    "bathHeatingStatusSensor",
    "bathroomHeaterDryer",
    "co2Sensor",
    "coldOrHotWaterHeatSourceEquipment",
    "commercialAirConditionerIndoorUnit",
    "commercialAirConditionerOutdoorUnit",
    "commercialShowcase",
    "commercialShowcaseOutdoorUnit",
    "controller",
    "cookingHeater",
    "currentSensor",
    "drElectricEnergyMeter",
    "electricEnergySensor",
    "electricLock",
    "electricRainDoor",
    "electricWaterHeater",
    "emergencyButton",
    "enhancedLightingSystem",
    "evCharger",
    "evChargerDischarger",
    "floorHeater",
    "fuelCell",
    "gasMeter",
    "generalLighting",
    "homeAirConditioner",
    "humanDetectionSensor",
    "humiditySensor",
    "hvSmartElectricEnergyMeter",
    "hybridWaterHeater",
    "illuminanceSensor",
    "instantaneousWaterHeater",
    "lightingSystem",
    "lvSmartElectricEnergyMeter",
    "monoFunctionalLighting",
    "powerDistributionBoardMetering",
    "pvPowerGeneration",
    "refrigerator",
    "riceCooker",
    "smartElectricEnergySubMeter",
    "storageBattery",
    "switch",
    "temperatureSensor",
    "tv",
    "ventilationFan",
    "vocSensor",
    "washerDryer",
    "waterFlowMeter",
    "wattHourMeter",
  ],
};
